package com.engfred.musicplayer.core.constants

const val COMMAND_UPDATE_AUDIO_SESSION_ID = "UPDATE_AUDIO_SESSION_ID"
const val COMMAND_REQUEST_AUDIO_SESSION_ID = "REQUEST_AUDIO_SESSION_ID"
const val KEY_AUDIO_SESSION_ID = "KEY_AUDIO_SESSION_ID"